lang: "es"
groups:
  ENG:
    private: false
    prefix: "&7[ENG]&r "
    max-members: 30 #Use 0 if unlimited
  ESP:
    private: false
    prefix: "&7[ESP]&r "
    max-members: 30
  ADMIN:
    private: false
    prefix: "&7[ADMIN]&r "
    max-members: 30