groups:
  ENG:
    prefix: "&7[ENG] "
    color: BLUE
    max-members: 30
  ESP:
    prefix: "&7[ESP] "
    color: RED
    max-members: 30

translation:
  provider: "deepL" # or "google", "microsoft"
  api-key: "super-secret-api-key"
  placeholder_handling: true
  excluded_placeholders:
    - "%player%"
    - "{money}"
    - "%time%"
  cache:
    memory_ttl: 3600 # 1 hour
    db_persist: true